### PR TITLE
Feature/29 fix health check

### LINKED ISSUE #29: Fix health check
The healthcheck in k8s-ces-control does not work as expected. There should be a container healthcheck that always returns true as long as there is at least one replica scaled in the dogu deployment. This indicates for admin dogu that a container is in the "starting" state. Otherwise there would be only started and stopped. And the state would still be stopped for the whole starting time which would confuse admin dogu users.

### PR DESCRIPTION
**Pull request by sklein94**
Resolves #29

### CODE REVIEW

File: packages/doguAdministration/service.go [hunk 1]
```diff
@@ -102,7 +109,7 @@ func (s *server) GetDoguList(ctx context.Context, _ *pb.DoguListRequest) (*pb.Do
 		return nil, err
 	}
 
-	return createDoguListResponse(doguJsonList), nil
+	return s.createDoguListResponse(doguJsonList), nil
```
Comment (cesmarvin) [inline packages/doguAdministration/service.go:112]: 🚫 **[checkstyle]** <contextcheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Function `createDoguListResponse` should pass the context parameter

**Review by kahoona77 — APPROVED** [review]
LGTM
